# Generated by Django 3.1.5 on 2021-02-03 08:03

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('file_field', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='D:\\File_Sharing_app\\app\\media/my_sell/'), upload_to=myApp.models.image_directory_path)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('share', models.ManyToManyField(blank=True, related_name='SharedUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
