# Generated by Django 3.1.5 on 2021-01-23 19:12

import django.core.files.storage
from django.db import migrations, models
import myApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_field',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='D:\\File_Sharing_app\\app\\media/my_sell/'), upload_to=myApp.models.image_directory_path),
        ),
    ]
